function contract = model_contract()
%MODEL_CONTRACT Explicit ONNX tensor contracts for every sub-model.
%
%   contract = MODEL_CONTRACT()
%
%   Returns a struct with fields: encoder, decoder, decoder_with_past,
%   vocoder, spk_encoder.  Each entry lists:
%     .file          – relative path under models/
%     .inputs        – struct array with .name .dtype .shape .desc
%     .outputs       – struct array with .name .dtype .shape .desc
%     .notes         – free text on ordering / dynamic axes

cfg = pipeline_config();

contract = struct();

% --- Encoder ------------------------------------------------------------
contract.encoder.file = cfg.paths.encoder;
contract.encoder.inputs = struct( ...
    'name', {'input_ids', 'attention_mask'}, ...
    'dtype', {'int64', 'int64'}, ...
    'shape', {'[B,T]', '[B,T]'}, ...
    'desc', {'token IDs including BOS/EOS [0,80]', '1 for real tokens, 0 for pad'} ...
);
contract.encoder.outputs = struct( ...
    'name', {'last_hidden_state'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,T,768]'}, ...
    'desc', {'encoder hidden states'} ...
);
contract.encoder.notes = 'Batch B=1 at inference. T dynamic (seq len +2). Hidden dim 768.';

% --- Decoder (first step) -----------------------------------------------
contract.decoder.file = cfg.paths.decoder;
contract.decoder.inputs = struct( ...
    'name', {'input_ids', 'encoder_hidden_states', 'encoder_attention_mask', 'speaker_embeddings'}, ...
    'dtype', {'int64', 'float32', 'int64', 'float32'}, ...
    'shape', {'[B,1]', '[B,T,768]', '[B,T]', '[B,512]'}, ...
    'desc', {'decoder start token (0)', 'encoder hidden_states from encoder', 'same mask as encoder', 'L2-normalised speaker embedding'} ...
);
contract.decoder.outputs = struct( ...
    'name', {'logits', 'past_key_values'}, ...
    'dtype', {'float32', 'float32'}, ...
    'shape', {'[B,1,80] or [B,1,81] inc stop', '[B,n_heads,seq,head_dim] x layers*2'}, ...
    'desc', {'predicted Mel frame 80 bins (+ optional stop)', 'KV cache for next step'} ...
);
contract.decoder.notes = ['First autoregressive step. Past KV is output for decoder_with_past. ' ...
    'Output logits last dim 80 Mel bins. Some exports append 1 stop logit -> check dim.'];

% --- Decoder with past --------------------------------------------------
contract.decoder_with_past.file = cfg.paths.decoder_kv;
contract.decoder_with_past.inputs = struct( ...
    'name', {'input_ids', 'encoder_hidden_states', 'encoder_attention_mask', 'speaker_embeddings', 'past_key_values.*'}, ...
    'dtype', {'int64', 'float32', 'int64', 'float32', 'float32'}, ...
    'shape', {'[B,1]', '[B,T,768]', '[B,T]', '[B,512]', '[B,n_heads,prev_len,head_dim]'}, ...
    'desc', {'previous predicted token / frame id', 'encoder states (constant)', 'encoder mask (constant)', 'speaker embedding (constant)', 'KV cache from prev step'} ...
);
contract.decoder_with_past.outputs = contract.decoder.outputs;
contract.decoder_with_past.notes = 'Loop: feed prev frame id + updated KV each step until stop or max_len.';

% --- Vocoder ------------------------------------------------------------
contract.vocoder.file = cfg.paths.vocoder;
contract.vocoder.inputs = struct( ...
    'name', {'spectrogram'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,80,T] or [1,80,T]'}, ...
    'desc', {'log-Mel or Mel spectrogram, 80 bins, time axis last'} ...
);
contract.vocoder.outputs = struct( ...
    'name', {'waveform'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,1,T*256] or [B,T*256]'}, ...
    'desc', {'mono 16 kHz waveform, 256x upsample factor'} ...
);
contract.vocoder.notes = 'Input Mel must be float32, not dB vs log mismatch. Output peak-normalised later.';

% --- Speaker encoder (CAM++ 512) ----------------------------------------
contract.spk_encoder.file = cfg.paths.spk_encoder;
contract.spk_encoder.inputs = struct( ...
    'name', {'features'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,T,80]'}, ...
    'desc', {'80-dim log-Mel filterbank with CMN, 25ms win 10ms hop, 20-8000 Hz'} ...
);
contract.spk_encoder.outputs = struct( ...
    'name', {'embedding'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,512]'}, ...
    'desc', {'512-dim speaker embedding, pre L2-norm'} ...
);
contract.spk_encoder.notes = 'Raw waveform -> fbank80 -> CMN -> ONNX -> L2 normalise. Chunk long audio.';

% --- Cross-check against pipeline_config onnx field (single source of truth)
cfgOnnx = cfg.onnx;
assert(isequal(cfgOnnx.encoder_inputs, {contract.encoder.inputs.name}), 'pipeline_config vs model_contract encoder inputs mismatch');
assert(isequal(cfgOnnx.spk_inputs, {contract.spk_encoder.inputs.name}), 'pipeline_config vs model_contract spk inputs mismatch');

end
