function contract = model_contract()
%MODEL_CONTRACT Machine-readable ONNX tensor contracts for all 5 sub-models.
%
%   contract = MODEL_CONTRACT()
%
%   Updated with authoritative runtime contracts verified in MATLAB R2026a:
%     1. Encoder: input_ids [1, T] format UU (NO attention_mask input)
%     2. Decoder step 1: speaker_embeddings, encoder_hidden_state, output_sequence,
%        encoder_attention_mask -> spectrumOutput, probOutput, + 24 present KV
%     3. Decoder with past: speaker_embeddings, 24 past KV inputs, output_sequence,
%        encoder_attention_mask -> spectrumOutput, probOutput, + 12 decoder present KV
%     4. HiFi-GAN Vocoder: spectrogram [T_mel, 80] format UU -> waveformOutput [1, 1, T*256]
%     5. CAM++ Speaker Encoder: feats [1, T, 80] format UUU -> embsOutput [1, 512]

cfg = pipeline_config();

contract = struct();

% -------------------------------------------------------------------------
% 1. SpeechT5 Text Encoder
% -------------------------------------------------------------------------
contract.encoder = struct();
contract.encoder.file = cfg.paths.encoder;
contract.encoder.source = "Xenova/speecht5_tts (onnx/encoder_model.onnx, opset 14)";
contract.encoder.status = "VERIFIED_R2026A";
contract.encoder.verificationStatus = "VERIFIED_IMPORT_CONTRACT";
contract.encoder.needsOnlineVerification = false;
contract.encoder.notes = "Verified in R2026a: single input 'input_ids' [1, T] format UU. No attention_mask input.";

contract.encoder.expected = struct();
contract.encoder.expected.inputs = struct( ...
    'name', {'input_ids'}, ...
    'dtype', {'int64'}, ...
    'shape', {'[1, T]'}, ...
    'format', {'UU'}, ...
    'desc', {'token IDs in [0, 80] (EOS appended, no BOS)'} ...
);
contract.encoder.expected.outputs = struct( ...
    'name', {'last_hidden_state'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[1, T, 768]'}, ...
    'desc', {'encoder contextual representations for decoder cross-attention'} ...
);
contract.encoder.observed = struct('inputNames', "input_ids", 'outputNames', ["encoder_outputsOutput", "encoder_attention_maOutput"], 'inspected', true);

% -------------------------------------------------------------------------
% 2. SpeechT5 Autoregressive Decoder (First Step)
% -------------------------------------------------------------------------
contract.decoder = struct();
contract.decoder.file = cfg.paths.decoder;
contract.decoder.source = "Xenova/speecht5_tts (onnx/decoder_model.onnx, opset 14)";
contract.decoder.status = "VERIFIED_R2026A";
contract.decoder.verificationStatus = "VERIFIED_IMPORT_CONTRACT";
contract.decoder.needsOnlineVerification = false;
contract.decoder.notes = "Verified in R2026a: inputs are speaker_embeddings, encoder_hidden_state, output_sequence, encoder_attention_ma. Outputs are spectrumOutput, probOutput, output_sequence_..., plus 24 present KV tensors.";

contract.decoder.expected = struct();
contract.decoder.expected.inputs = struct( ...
    'name', {'speaker_embeddings', 'encoder_hidden_state', 'output_sequence', 'encoder_attention_ma'}, ...
    'dtype', {'float32', 'float32', 'float32', 'int64'}, ...
    'shape', {'[1, 512]', '[1, T, 768]', '[1, 1, 80]', '[1, T]'}, ...
    'format', {'UU', 'UUU', 'UUU', 'UU'}, ...
    'desc', {'L2-normalized 512-dim speaker vector', 'encoder hidden representation [1, T, 768]', 'starting zero-Mel frame [1, 1, 80]', 'encoder token mask [1, T]'} ...
);
contract.decoder.expected.outputs = struct( ...
    'name', {'spectrumOutput', 'probOutput'}, ...
    'dtype', {'float32', 'float32'}, ...
    'shape', {'[rf, 80]', '[1, rf]'}, ...
    'desc', {'predicted Mel frames (rf=2)', 'calibrated stop probability/logits per frame'} ...
);
contract.decoder.observed = struct('pastCount', 24, 'inspected', true);

% -------------------------------------------------------------------------
% 3. SpeechT5 Decoder With Past (KV Cache Loop)
% -------------------------------------------------------------------------
contract.decoder_with_past = struct();
contract.decoder_with_past.file = cfg.paths.decoder_with_past;
contract.decoder_with_past.source = "Xenova/speecht5_tts (onnx/decoder_with_past_model.onnx, opset 14)";
contract.decoder_with_past.status = "VERIFIED_R2026A";
contract.decoder_with_past.verificationStatus = "VERIFIED_IMPORT_CONTRACT";
contract.decoder_with_past.needsOnlineVerification = false;
contract.decoder_with_past.notes = "Verified in R2026a: 24 past KV inputs (12 decoder + 12 encoder) + speaker_embeddings + output_sequence + encoder_attention_mask. Outputs spectrumOutput, probOutput, output_sequence_..., + 12 updated decoder present KV.";

contract.decoder_with_past.expected = struct();
contract.decoder_with_past.expected.inputs = struct( ...
    'name', {'speaker_embeddings', 'output_sequence', 'encoder_attention_mask'}, ...
    'dtype', {'float32', 'float32', 'int64'}, ...
    'shape', {'[1, 512]', '[1, 1, 80]', '[1, T]'}, ...
    'format', {'UU', 'UUU', 'UU'}, ...
    'desc', {'speaker embedding', 'last predicted Mel frame [1, 1, 80]', 'encoder token mask [1, T] (plus 24 past KV UUUU)'} ...
);
contract.decoder_with_past.expected.outputs = contract.decoder.expected.outputs;
contract.decoder_with_past.observed = struct('pastInCount', 24, 'pastOutCount', 12, 'inspected', true);

% -------------------------------------------------------------------------
% 4. HiFi-GAN Neural Vocoder
% -------------------------------------------------------------------------
contract.vocoder = struct();
contract.vocoder.file = cfg.paths.vocoder;
contract.vocoder.source = "Xenova/speecht5_hifigan (onnx/model.onnx, opset 14)";
contract.vocoder.status = "VERIFIED_R2026A";
contract.vocoder.verificationStatus = "VERIFIED_IMPORT_CONTRACT";
contract.vocoder.needsOnlineVerification = false;
contract.vocoder.notes = "Verified in R2026a: input is 'spectrogram' shape [T_mel, 80] format UU. Output is 'waveformOutput' [1, 1, T*256].";

contract.vocoder.expected = struct();
contract.vocoder.expected.inputs = struct( ...
    'name', {'spectrogram'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[T_mel, 80]'}, ...
    'format', {'UU'}, ...
    'desc', {'natural log-Mel acoustic features, [T_mel, 80] raw ONNX orientation'} ...
);
contract.vocoder.expected.outputs = struct( ...
    'name', {'waveformOutput'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[1, 1, T*256]'}, ...
    'desc', {'discrete-time 16 kHz speech sequence'} ...
);
contract.vocoder.observed = struct('inputNames', "spectrogram", 'outputNames', "waveformOutput", 'inspected', true);

% -------------------------------------------------------------------------
% 5. Speaker Embedding Encoder (CAM++)
% -------------------------------------------------------------------------
contract.spk_encoder = struct();
contract.spk_encoder.file = cfg.paths.spk_encoder;
contract.spk_encoder.source = "openspeech/wespeaker-models (voxceleb_CAM++.onnx)";
contract.spk_encoder.status = "IMPORTED_WITH_PLACEHOLDERS";
contract.spk_encoder.verificationStatus = "OPERATOR_COMPATIBILITY_INVESTIGATION";
contract.spk_encoder.needsOnlineVerification = true;
contract.spk_encoder.notes = "Verified in R2026a: importNetworkFromONNX succeeds (input 'feats' [1, T, 80] UUU, output 'embsOutput' [1, 512]), but reports unsupported AveragePool ceil_mode configuration and BatchNormalization training_mode.";

contract.spk_encoder.expected = struct();
contract.spk_encoder.expected.inputs = struct( ...
    'name', {'feats'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[1, T, 80]'}, ...
    'format', {'UUU'}, ...
    'desc', {'80-dim log-Mel filterbank with CMN [1, T, 80] format UUU'} ...
);
contract.spk_encoder.expected.outputs = struct( ...
    'name', {'embsOutput'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[1, 512]'}, ...
    'desc', {'512-dimensional speaker embedding vector'} ...
);
contract.spk_encoder.observed = struct('inputNames', "feats", 'outputNames', "embsOutput", 'inspected', true);

end
