function contract = model_contract()
%MODEL_CONTRACT Machine-readable ONNX tensor contracts for all 5 sub-models.
%
%   contract = MODEL_CONTRACT()
%
%   Structure per sub-model:
%     .file                   – Canonical path from pipeline_config()
%     .source                 – Official Hugging Face repository / model source
%     .status                 – "UNVERIFIED" | "OBSERVED" | "VERIFIED" | "FAILED"
%     .verificationStatus     – Detailed verification milestone description
%     .needsOnlineVerification– Logical true until validated on MATLAB Online
%     .notes                  – Context on expectations vs verification status
%     .expected               – Struct with expected inputs and outputs:
%                               .inputs: struct array (.name, .dtype, .shape, .format, .desc)
%                               .outputs: struct array (.name, .dtype, .shape, .desc)
%     .observed               – Struct populated dynamically when model is imported
%
%   Consumed canonically by:
%     validate_models.m, diagnose_onnx.m, synthesize_features.m,
%     load_onnx_engine.m, test_*.m

cfg = pipeline_config();

contract = struct();

% -------------------------------------------------------------------------
% 1. SpeechT5 Text Encoder
% -------------------------------------------------------------------------
contract.encoder = struct();
contract.encoder.file = cfg.paths.encoder;
contract.encoder.source = "Xenova/speecht5_tts (onnx/encoder_model.onnx, opset 14)";
contract.encoder.status = "UNVERIFIED";
contract.encoder.verificationStatus = "PENDING_ONLINE_INSPECTION";
contract.encoder.needsOnlineVerification = true;
contract.encoder.notes = "Expected: int64 input_ids [B,T] (EOS only, no BOS) + attention_mask [B,T] -> last_hidden_state [B,T,768].";

contract.encoder.expected = struct();
contract.encoder.expected.inputs = struct( ...
    'name', {'input_ids', 'attention_mask'}, ...
    'dtype', {'int64', 'int64'}, ...
    'shape', {'[B,T]', '[B,T]'}, ...
    'format', {'CB', 'CB'}, ...
    'desc', {'token IDs (EOS appended, no BOS) in [0,80]', '1 for real tokens, 0 for pad'} ...
);
contract.encoder.expected.outputs = struct( ...
    'name', {'last_hidden_state'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,T,768]'}, ...
    'desc', {'encoder contextual representations for decoder cross-attention'} ...
);

contract.encoder.observed = struct('inputNames', strings(0,1), 'outputNames', strings(0,1), 'shapes', struct(), 'inspected', false);

% -------------------------------------------------------------------------
% 2. SpeechT5 Autoregressive Decoder (First Step)
% -------------------------------------------------------------------------
contract.decoder = struct();
contract.decoder.file = cfg.paths.decoder;
contract.decoder.source = "Xenova/speecht5_tts (onnx/decoder_model.onnx, opset 14)";
contract.decoder.status = "UNVERIFIED";
contract.decoder.verificationStatus = "PENDING_ONLINE_INSPECTION";
contract.decoder.needsOnlineVerification = true;
contract.decoder.notes = "Expected: float output_sequence [B,1,80] (zero start) + encoder hidden [B,T,768] + mask [B,T] + spk [B,512] -> spectrum [B,rf,80] + prob [B,rf] + initial KV tensors (rf=2).";

contract.decoder.expected = struct();
contract.decoder.expected.inputs = struct( ...
    'name', {'output_sequence', 'encoder_hidden_states', 'encoder_attention_mask', 'speaker_embeddings'}, ...
    'dtype', {'float32', 'float32', 'int64', 'float32'}, ...
    'shape', {'[B,1,80]', '[B,T,768]', '[B,T]', '[B,512]'}, ...
    'format', {'CBT', 'CB', 'CB', 'CB'}, ...
    'desc', {'starting zero-Mel frame [1,1,80]', 'encoder hidden_states [1,T,768]', 'encoder mask [1,T]', 'L2-normalized 512-dim speaker vector'} ...
);
contract.decoder.expected.outputs = struct( ...
    'name', {'spectrum', 'prob'}, ...
    'dtype', {'float32', 'float32'}, ...
    'shape', {'[B,rf,80]', '[B,rf]'}, ...
    'desc', {'predicted Mel frames (rf=2)', 'stop logits / probability per frame'} ...
);

contract.decoder.observed = struct('inputNames', strings(0,1), 'outputNames', strings(0,1), 'shapes', struct(), 'pastCount', 0, 'inspected', false);

% -------------------------------------------------------------------------
% 3. SpeechT5 Decoder With Past (KV Cache Loop)
% -------------------------------------------------------------------------
contract.decoder_with_past = struct();
contract.decoder_with_past.file = cfg.paths.decoder_kv;
contract.decoder_with_past.source = "Xenova/speecht5_tts (onnx/decoder_with_past_model.onnx, opset 14)";
contract.decoder_with_past.status = "UNVERIFIED";
contract.decoder_with_past.verificationStatus = "PENDING_ONLINE_INSPECTION";
contract.decoder_with_past.needsOnlineVerification = true;
contract.decoder_with_past.notes = "Expected: last predicted Mel frame [B,1,80] + encoder context + speaker embedding + past_key_values.* -> spectrum + prob + updated past_key_values.*.";

contract.decoder_with_past.expected = struct();
contract.decoder_with_past.expected.inputs = struct( ...
    'name', {'output_sequence', 'encoder_hidden_states', 'encoder_attention_mask', 'speaker_embeddings'}, ...
    'dtype', {'float32', 'float32', 'int64', 'float32'}, ...
    'shape', {'[B,1,80]', '[B,T,768]', '[B,T]', '[B,512]'}, ...
    'format', {'CBT', 'CB', 'CB', 'CB'}, ...
    'desc', {'last emitted Mel frame [1,1,80]', 'encoder states', 'encoder mask', 'speaker embedding'} ...
);
contract.decoder_with_past.expected.outputs = contract.decoder.expected.outputs;

contract.decoder_with_past.observed = struct('inputNames', strings(0,1), 'outputNames', strings(0,1), 'pastInCount', 0, 'pastOutCount', 0, 'hasUseCache', false, 'inspected', false);

% -------------------------------------------------------------------------
% 4. HiFi-GAN Neural Vocoder
% -------------------------------------------------------------------------
contract.vocoder = struct();
contract.vocoder.file = cfg.paths.vocoder;
contract.vocoder.source = "Xenova/speecht5_hifigan (onnx/model.onnx, opset 14)";
contract.vocoder.status = "UNVERIFIED";
contract.vocoder.verificationStatus = "PENDING_ONLINE_INSPECTION";
contract.vocoder.needsOnlineVerification = true;
contract.vocoder.notes = "Expected: natural log-Mel spectrogram [1,80,T] (80 bins, 80-7600 Hz, SCB) -> 16 kHz mono waveform [1,1,T*256].";

contract.vocoder.expected = struct();
contract.vocoder.expected.inputs = struct( ...
    'name', {'spectrogram'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,80,T]'}, ...
    'format', {'SCB'}, ...
    'desc', {'natural log-Mel acoustic features, 80 bins'} ...
);
contract.vocoder.expected.outputs = struct( ...
    'name', {'waveform'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,1,T*256]'}, ...
    'desc', {'mono 16 kHz discrete-time speech sequence (256x upsampling factor)'} ...
);

contract.vocoder.observed = struct('inputNames', strings(0,1), 'outputNames', strings(0,1), 'inspected', false);

% -------------------------------------------------------------------------
% 5. Speaker Embedding Encoder (CAM++)
% -------------------------------------------------------------------------
contract.spk_encoder = struct();
contract.spk_encoder.file = cfg.paths.spk_encoder;
contract.spk_encoder.source = "openspeech/wespeaker-models (voxceleb_CAM++.onnx)";
contract.spk_encoder.status = "UNVERIFIED";
contract.spk_encoder.verificationStatus = "PENDING_ONLINE_INSPECTION";
contract.spk_encoder.needsOnlineVerification = true;
contract.spk_encoder.notes = "Expected: 80-bin filterbank with CMN [1,T,80] CBT input 'features' -> 512-dim raw embedding [1,512], then L2 normalized.";

contract.spk_encoder.expected = struct();
contract.spk_encoder.expected.inputs = struct( ...
    'name', {'features'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,T,80]'}, ...
    'format', {'CBT'}, ...
    'desc', {'80-dim log-Mel filterbank with CMN (25 ms window, 10 ms hop)'} ...
);
contract.spk_encoder.expected.outputs = struct( ...
    'name', {'embedding'}, ...
    'dtype', {'float32'}, ...
    'shape', {'[B,512]'}, ...
    'desc', {'512-dimensional speaker embedding vector'} ...
);

contract.spk_encoder.observed = struct('inputNames', strings(0,1), 'outputNames', strings(0,1), 'inspected', false);

end
